name: Manual Trigger Example

on: push
  

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      

      - name: docker setup
        run: docker/setup-docker-action@v4

      - name: echo docker detais
        run: docker info

      - name: run image
        run: docker run hello-world






